Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp-education/ubuntu-24-04"

  config.vm.box_version = "0.1.0"

  config.vm.provision "shell", name: "install-dependencies", path: "install-dependencies.sh"

  config.vm.provision "shell", name: "start-terramino", inline: <<-SHELL
    cd /home/vagrant/terramino-go
    docker compose up -d
  SHELL

  config.vm.provision "shell", name: "restart-terramino", run: "never", inline: <<-SHELL
    docker compose restar
  SHELL

  config.vm.provision "shell", name: "reload-terramino", run: "never", inline: <<-SHELL
    /usr/local/bin/reload-terramino
  SHELL
end
