Vagrant.configure("2") do |config|
  # image
  config.vm.box = "hashicorp-education/ubuntu-24-04"

  config.vm.box_version = "0.1.0"

  # script
  config.vm.provision "shell", name: "install-dependencies", path: "install-dependencies.sh"
  config.vm.provision "shell", name: "start-terramino", inline: <<-SHELL
    cd /home/vagrant/terramino-go
    docker compose up -d
  SHELL
  config.vm.provision "shell", name: "restart-terramino", run: "never", inline: <<-SHELL
    docker compose restar
  SHELL
  config.vm.provision "shell", name: "reload-terramino", run: "never", inline: <<-SHELL
    /usr/local/bin/reload-terramino
  SHELL

  # ports (8080 for frontend, 8081 for backend)
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 8081, host: 8081

  # volume terramino-go directory
  config.vm.synced_folder "./terramino-go", "/home/vagrant/terramino-go", create:true 

end
