Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end

  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.provision "shell", path: "./scripts/install.sh", name: "installation"
  config.vm.provision "shell", path: "./scripts/setup.sh", name: "setup"
end
