Vagrant.configure("2") do |config|
	config.vm.box = "debian/bookworm64"
  config.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
  end

  #expose argocd
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  #expose playground
  config.vm.network "forwarded_port", guest: 8888, host: 8888
  config.vm.provision "shell", path: "./scripts/install.sh", name: "installation"
  config.vm.provision "shell", path: "./scripts/setup.sh", name: "setup"
  config.vm.provision "shell", path: "./scripts/port-forward.sh", name: "port-forward", run: "always"
end
